apiVersion: apps/v1
kind: Deployment
metadata:
  name: lca-service-app-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lca-service-app
  template:
    metadata:
      labels:
        app: lca-service-app
    spec:
      containers:
      - name: lca-service-app
        image: asia-south1-docker.pkg.dev/genuine-wording-362504/lca-service-app/lca-ai-service:latest
        ports:
        - containerPort: 8080  
        env:  
          - name: PORT
            value: "8080"
        resources:
          requests:
            cpu: "2"
            memory: 8Gi
            ephemeral-storage: 10Gi
          limits:
            cpu: "2"
            memory: 8Gi
            ephemeral-storage: 10Gi
