version: "3.9"
services:
  law-service:
    container_name: law-service-app
    build: .
    ports:
      - "8081:8081"
    networks:
      - legal-net

networks:
  legal-net:
    name: law-network 
    external: true